import { Inter } from 'next/font/google'
import './globals.css'
import style from './page.module.css'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={inter.style}>
      <body className={style.body}>{children}</body>
    </html>
  )
}
